USE [master]
GO
/****** Object:  Database [PRA-FICHTE]    Script Date: 28.10.2024. 17:22:13 ******/
CREATE DATABASE [PRA-FICHTE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRA-FICHTE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PRA-FICHTE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRA-FICHTE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PRA-FICHTE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PRA-FICHTE] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRA-FICHTE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PRA-FICHTE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET ARITHABORT OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PRA-FICHTE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PRA-FICHTE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PRA-FICHTE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PRA-FICHTE] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PRA-FICHTE] SET  MULTI_USER 
GO
ALTER DATABASE [PRA-FICHTE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PRA-FICHTE] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PRA-FICHTE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PRA-FICHTE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PRA-FICHTE] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PRA-FICHTE] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PRA-FICHTE] SET QUERY_STORE = ON
GO
ALTER DATABASE [PRA-FICHTE] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PRA-FICHTE]
GO
/****** Object:  Table [dbo].[Friend]    Script Date: 28.10.2024. 17:22:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Friend](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SenderID] [int] NOT NULL,
	[RecieverID] [int] NOT NULL,
	[DateSent] [datetime2](7) NOT NULL,
	[isAccepted] [bit] NOT NULL,
 CONSTRAINT [PK_Friend] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Group]    Script Date: 28.10.2024. 17:22:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Group](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[DateCreated] [datetime2](7) NOT NULL,
	[ImageID] [int] NOT NULL,
 CONSTRAINT [PK_Group] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GroupUser]    Script Date: 28.10.2024. 17:22:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GroupUser](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[GroupID] [int] NOT NULL,
 CONSTRAINT [PK_GroupUser] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Image]    Script Date: 28.10.2024. 17:22:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Image](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Path] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_Image] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Message]    Script Date: 28.10.2024. 17:22:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Message](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DateCreated] [datetime2](7) NOT NULL,
	[Content] [nvarchar](2048) NOT NULL,
	[DateRead] [datetime2](7) NULL,
	[UserID] [int] NOT NULL,
	[GroupID] [int] NOT NULL,
	[ImageID] [int] NULL,
 CONSTRAINT [PK_Message] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 28.10.2024. 17:22:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nchar](10) NOT NULL,
	[DateJoined] [datetime2](7) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[IsAdmin] [bit] NOT NULL,
	[ImageID] [int] NULL,
	[PwdHash] [nvarchar](256) NOT NULL,
	[PwdSalt] [nvarchar](256) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Friend]  WITH CHECK ADD  CONSTRAINT [FK_Friend_User] FOREIGN KEY([SenderID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[Friend] CHECK CONSTRAINT [FK_Friend_User]
GO
ALTER TABLE [dbo].[Friend]  WITH CHECK ADD  CONSTRAINT [FK_Friend_User1] FOREIGN KEY([RecieverID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[Friend] CHECK CONSTRAINT [FK_Friend_User1]
GO
ALTER TABLE [dbo].[Group]  WITH CHECK ADD  CONSTRAINT [FK_Group_Image] FOREIGN KEY([ImageID])
REFERENCES [dbo].[Image] ([ID])
GO
ALTER TABLE [dbo].[Group] CHECK CONSTRAINT [FK_Group_Image]
GO
ALTER TABLE [dbo].[GroupUser]  WITH CHECK ADD  CONSTRAINT [FK_GroupUser_Group] FOREIGN KEY([GroupID])
REFERENCES [dbo].[Group] ([ID])
GO
ALTER TABLE [dbo].[GroupUser] CHECK CONSTRAINT [FK_GroupUser_Group]
GO
ALTER TABLE [dbo].[GroupUser]  WITH CHECK ADD  CONSTRAINT [FK_GroupUser_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[GroupUser] CHECK CONSTRAINT [FK_GroupUser_User]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_Group] FOREIGN KEY([GroupID])
REFERENCES [dbo].[Group] ([ID])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_Group]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_Image] FOREIGN KEY([ImageID])
REFERENCES [dbo].[Image] ([ID])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_Image]
GO
ALTER TABLE [dbo].[Message]  WITH CHECK ADD  CONSTRAINT [FK_Message_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[Message] CHECK CONSTRAINT [FK_Message_User]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_Image] FOREIGN KEY([ImageID])
REFERENCES [dbo].[Image] ([ID])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_Image]
GO
USE [master]
GO
ALTER DATABASE [PRA-FICHTE] SET  READ_WRITE 
GO
